# Generated by Django 2.2.3 on 2019-07-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='priceHour',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
