# Generated by Django 2.2.3 on 2019-07-27 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190727_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='rotaryMotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField(blank=True, null=True)),
                ('priceHour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paid', models.BooleanField(default=False)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='core.Vehicle')),
            ],
        ),
    ]
