# Generated by Django 2.2.3 on 2019-07-27 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rotarymotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotarymotion',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleRotary', to='core.Vehicle'),
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('priceMouth', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicleMounth', to='core.Vehicle')),
            ],
        ),
    ]
