# Generated by Django 2.2.3 on 2019-07-27 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190726_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotaryMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payDay', models.DateField()),
                ('totaPaid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('monthly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly', to='core.Monthly')),
            ],
        ),
    ]
